name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  spm:
    name: SPM Build Xcode 16
    runs-on: macos-15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.app/Contents/Developer
      - name: Build and Test Framework
        run: swift test
  readme-validation:
    name: Check Markdown links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Link Checker
        uses: AlexanderDokuchaev/md-dead-link-check@v1.0.1
  lint-swift:
    name: Lint Swift
    runs-on: ubuntu-latest
    container: swift:6.0
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Lint Swift
        run: swift run --package-path CLI swiftformat --swiftversion 6.0 . --lint
