name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  spm:
    name: SPM Build Xcode 16
    runs-on: macos-15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Select Xcode Version
        run: sudo xcode-select --switch /Applications/Xcode_16.app/Contents/Developer
      - name: Build and Test Framework
        run: swift test
